[package]
name = "crab8-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macros = true
crate-type = ["proc-macro"]

[dependencies]
crab8-core = {path="../crab8-core"}
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
